CREATE TABLE BRANCH(
    BRANCH_NAME VARCHAR2(25),
    BRANCHCITY VARCHAR2(25),
    ASSETS REAL,
    PRIMARY KEY(BRANCH_NAME)
    );

CREATE TABLE ACCOUNTS(
    ACCNO INT,
    BRANCH_NAME VARCHAR2(25),
    BALANCE REAL,
    PRIMARY KEY(ACCNO),
    FOREIGN KEY(BRANCH_NAME) REFERENCES BRANCH(BRANCH_NAME) ON DELETE CASCADE
    );

CREATE TABLE CUSTOMER(
    CUSTOMER_NAME VARCHAR(25),
    CUSTOMER_STREET VARCHAR2(25),
    CUSTOMER_CITY VARCHAR2(25),
    PRIMARY KEY(CUSTOMER_NAME)
    );
    
CREATE TABLE DEPOSITOR(
    CUSTOMER_NAME VARCHAR(25),
    ACCNO INT,
    PRIMARY KEY(CUSTOMER_NAME, ACCNO),
    FOREIGN KEY(CUSTOMER_NAME) REFERENCES CUSTOMER(CUSTOMER_NAME) ON DELETE CASCADE,
    FOREIGN KEY(ACCNO) REFERENCES ACCOUNTS(ACCNO) ON DELETE CASCADE
    );

CREATE TABLE LOAN(
    LOAN_NUMBER INT,
    BRANCH_NAME VARCHAR2(25),
    AMOUNT REAL,
    PRIMARY KEY(LOAN_NUMBER),
    FOREIGN KEY(BRANCH_NAME) REFERENCES BRANCH(BRANCH_NAME) ON DELETE CASCADE
    );
    
CREATE TABLE BORROWER(
    CUSTOMER_NAME VARCHAR2(25),
    LOAN_NUMBER INT,
    PRIMARY KEY(CUSTOMER_NAME),
    FOREIGN KEY(CUSTOMER_NAME) REFERENCES CUSTOMER(CUSTOMER_NAME) ON DELETE CASCADE,
    FOREIGN KEY(LOAN_NUMBER) REFERENCES LOAN(LOAN_NUMBER) ON DELETE CASCADE
    );

INSERT INTO BRANCH VALUES('&BRANCH_NAME', '&BRANCHCITY', &ASSETS);
INSERT INTO ACCOUNTS VALUES(&ACCNO, '&BRANCH_NAME', &BALANCE);
INSERT INTO CUSTOMER VALUES('&CUSTOMER_NAME', '&CUSTOMER_STREET', '&CUSTOMER_CITY');
INSERT INTO DEPOSITOR VALUES('&CUSTOMER_NAME', &ACCNO);
INSERT INTO LOAN VALUES(&LOAN_NUMBER, '&BRANCH_NAME', &AMOUNT);
INSERT INTO BORROWER VALUES('&CUSTOMER_NAME', &LOAN_NUMBER);

SELECT * FROM BRANCH;
SELECT * FROM ACCOUNTS;
SELECT * FROM CUSTOMER;
SELECT * FROM DEPOSITOR;
SELECT * FROM LOAN;
SELECT * FROM BORROWER;
