CREATE TABLE PERSON(
	DRIVER_ID VARCHAR2(10),
	NAME VARCHAR2(20),
	ADDRESS VARCHAR2(15),
	PRIMARY KEY(DRIVER_ID)
	);

CREATE TABLE CAR(
	REGNO VARCHAR2(10),
	MODEL VARCHAR2(10),
	YEAR NUMBER(4),
	PRIMARY KEY(REGNO)
	);

CREATE TABLE ACCIDENT(
	REPORT_NO NUMBER(5),
	ADATE DATE,
	LOCATION VARCHAR2(15),
	PRIMARY KEY(REPORT_NO)
	);

CREATE TABLE OWNS(
	DRIVER_ID VARCHAR2(10),
	REGNO VARCHAR2(10),
	PRIMARY KEY(DRIVER_ID,REGNO),
	FOREIGN KEY(DRIVER_ID) REFERENCES PERSON(DRIVER_ID),
	FOREIGN KEY(REGNO) REFERENCES CAR(REGNO)
	);

CREATE TABLE PARTICIPATED(
	DRIVER_ID VARCHAR2(10),
	REGNO VARCHAR2(10),
	REPORT_NO NUMBER(5),
	DAMAGE_AMT NUMBER(7,2),
	PRIMARY KEY(DRIVER_ID,REGNO,REPORT_NO),
	FOREIGN KEY(DRIVER_ID,REGNO) REFERENCES OWNS(DRIVER_ID,REGNO) ON DELETE CASCADE,
	FOREIGN KEY(REPORT_NO) REFERENCES ACCIDENT(REPORT_NO) ON DELETE CASCADE
	);
    
-- INSERT 5 TUPLES EACH
INSERT INTO PERSON VALUES ('&DRIVER_ID','&NAME','&ADDRESS');

INSERT INTO CAR VALUES ('&REGNO','&MODEL',&YEAR);

INSERT INTO ACCIDENT VALUES (&REPORT_NO,'&ADATE','&LOCATION');

INSERT INTO OWNS VALUES ('&DRIVER_ID','&REGNO');

INSERT INTO PARTICIPATED VALUES ('&DRIVER_ID','&REGNO','&REPORT_NO',&DAMAGE_AMT);

-- PRINT EVERYTHING
SELECT * FROM PERSON;
SELECT * FROM CAR;
SELECT * FROM OWNS;
SELECT * FROM ACCIDENT;
SELECT * FROM PARTICIPATED;